version: "3"
services:
  parent-child-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: parent-child-ui:latest
    environment:
      - BUILD_ENV=dev
    ports:
      - 3000:3000
